Zwiki project backlog & notes

* ISSUES
** ImportError: No module named pagetypes.stx when pasting
2009-02-17T21:44:09 ERROR Zope.SiteErrorLog http://zope2.joyful.com/backup/manage_pasteObjects
Traceback (innermost last):
  Module ZPublisher.Publish, line 119, in publish
  Module ZPublisher.mapply, line 88, in mapply
  Module ZPublisher.Publish, line 42, in call_object
  Module OFS.CopySupport, line 220, in manage_pasteObjects
  Module OFS.CopySupport, line 576, in _getCopy
  Module ZODB.ExportImport, line 92, in importFile
  Module transaction._transaction, line 256, in savepoint
  Module transaction._transaction, line 253, in savepoint
  Module transaction._transaction, line 642, in __init__
  Module ZODB.Connection, line 1091, in savepoint
  Module ZODB.Connection, line 550, in _commit
  Module ZODB.ExportImport, line 178, in _importDuringCommit
ImportError: No module named pagetypes.stx

** UnicodeEncodeError in SplitterFunc
2009-02-17T15:56:14 BLATHER ZWiki failed to index KCRWPlaylistProofOfConceptRequirement
 Traceback (most recent call last):
  File "/zope2/Products/ZWiki/Catalog.py", line 112, in index_object
    self.catalog().catalog_object(self,self.url(),idxs)
  File "/zope-2.11.2/lib/python/Products/ZCatalog/ZCatalog.py", line 536, in catalog_object
    update_metadata=update_metadata)
  File "/zope-2.11.2/lib/python/Products/ZCatalog/Catalog.py", line 360, in catalogObject
    blah = x.index_object(index, object, threshold)
  File "/zope-2.11.2/lib/python/Products/PluginIndexes/TextIndex/TextIndex.py", line 313, in index_object
    for word in list(splitter(source,encoding=encoding)):
  File "/zope-2.11.2/lib/python/Products/PluginIndexes/TextIndex/Lexicon.py", line 167, in Splitter
    return self.SplitterFunc(astring, words)
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2019' in position 1034: ordinal not in range(128)

happens with production but not test server. After fiddling, recreating catalog and a restart, doesn't happen on production.

** empty recent changes in non-upgradeAll-ed wikis

** old favourite: IndexError: tuple index out of range while rendering an error message
Traceback (most recent call last):
  File "/zope-2.11.2/lib/python/OFS/SimpleItem.py", line 225, in raise_standardErrorMessage
    v = s(client, REQUEST, **kwargs)
  File "/zope-2.11.2/lib/python/OFS/DTMLMethod.py", line 144, in __call__
    r=apply(HTML.__call__, (self, client, REQUEST), kw)
  File "/zope-2.11.2/lib/python/DocumentTemplate/DT_String.py", line 476, in __call__
    try: result = render_blocks(self._v_blocks, md)
  File "/zope-2.11.2/lib/python/DocumentTemplate/DT_Let.py", line 75, in render
    else: d[name]=expr(md)
  File "/zope-2.11.2/lib/python/DocumentTemplate/DT_Util.py", line 196, in eval
    return eval(code, d)
  File "<string>", line 1, in <expression>
  File "/zope-2.11.2/lib/python/AccessControl/ZopeGuards.py", line 67, in guarded_getitem
    v = object[index]
IndexError: tuple index out of range

** TypeError: revision() takes exactly 2 arguments (1 given)
2009-02-14T11:56:52 ERROR Zope.SiteErrorLog http://zwiki.org/FrontPage/manage_change_history_page
Traceback (innermost last):
  Module ZPublisher.Publish, line 119, in publish
  Module ZPublisher.mapply, line 88, in mapply
  Module ZPublisher.Publish, line 42, in call_object
  Module Shared.DC.Scripts.Bindings, line 313, in __call__
  Module Shared.DC.Scripts.Bindings, line 350, in _bindAndExec
  Module App.special_dtml, line 178, in _exec
  Module DocumentTemplate.DT_In, line 703, in renderwob
TypeError: revision() takes exactly 2 arguments (1 given)

** NotImplementedError
2009-02-14T11:57:14 ERROR txn.1099901264 Failed to abort object: TransactionalUndo oid=<object object at 0x2ac16ca050a0>
Traceback (most recent call last):
  File "/zope-2.11.2/lib/python/transaction/_transaction.py", line 549, in abort
  File "/zope-2.11.2/lib/python/ZODB/DB.py", line 809, in abort
NotImplementedError

** AttributeError: 'list' object has no attribute 'decode'
2009-02-14T11:57:44 ERROR Zope.SiteErrorLog http://zwiki.org/IssueTracker
Traceback (innermost last):
  Module ZPublisher.Publish, line 119, in publish
  Module ZPublisher.mapply, line 88, in mapply
  Module ZPublisher.Publish, line 42, in call_object
  Module Products.ZWiki.ZWikiPage, line 231, in __call__
  Module Products.ZWiki.ZWikiPage, line 243, in render
  Module Products.ZWiki.plugins.pagetypes.rst, line 54, in render
  Module Products.ZWiki.ZWikiPage, line 308, in evaluatePreRenderedAsDtml
  Module OFS.DTMLDocument, line 132, in __call__
   - <ZWikiPage 'IssueTracker' at 0x2ab46d0>
   - URL: http://zwiki.org/IssueTracker/manage_main
   - Physical Path: /zwiki.org/IssueTracker
  Module DocumentTemplate.DT_String, line 476, in __call__
  Module DocumentTemplate.DT_Let, line 75, in render
  Module DocumentTemplate.DT_Util, line 196, in eval
   - __traceback_info__: tounicode
  Module <string>, line 1, in <expression>
  Module Products.ZWiki.Utils, line 586, in tounicode
  Module Products.ZWiki.Utils, line 602, in tounicode
AttributeError: 'list' object has no attribute 'decode'

** 2009-02-17T15:50:26 ERROR Zope.SiteErrorLog http://k.zwiki.org/K/setupCatalog
Traceback (innermost last):
  Module ZPublisher.Publish, line 125, in publish
  Module Zope2.App.startup, line 270, in commit
  Module transaction._manager, line 93, in commit
  Module transaction._transaction, line 325, in commit
  Module transaction._transaction, line 424, in _commitResources
  Module ZODB.Connection, line 541, in commit
  Module ZODB.Connection, line 586, in _commit
  Module ZODB.Connection, line 620, in _store_objects
  Module ZODB.serialize, line 407, in serialize
TypeError: Can't pickle objects in acquisition wrappers.

** 1354 expunge problems
* PRODUCT
** unicodegeddon
*** archive UnicodeGeddon notes from file:~/clients/wuwien/NOTES
** stabilisation
*** resolve issues in zwiki.org event log
*** test upgrading
**** get more upgrade testers
*** test search
*** test expunge
** release 1.0 & 2.0a1
** TESTS
*** cleanup, simplify, make easy and routine
*** test commits
** VIEWS AND SKINS
*** style for preview: http://phrogz.net/CSS/HowToDevelopWithCSS.html
*** cleanup, simplify, make custom skinning easy
** I18N
* PROCESS
** fix translations process
**** fix wrong zwiki.pot on launchpad
***** wait for https://translations.launchpad.net/zwiki/trunk/+imports?field.filter_status=NEEDS_REVIEW&field.filter_extension=all
**** see if launchpad po files get fixed
***** if not, re-upload
**** when fixed, download new ones if any
**** fix rosetta process
** patch review
*** find a new way to make patches visible, before or after commit
** notes
highlight active contributors, code and docs
author stats
automatic release
more automated release announcement, wider announcement
ditto release notes
auto testing
open commit - direct push/open send/approved send, reliable, clear instructions
better dev docs
CIA or other bot, darcs, issues etc. on irc
build dev community on darcs, irc & email
use ruby and haskell
hosting stats & cost reporting
* DOCS
** testimonials
*** call http://thread.gmane.org/gmane.comp.web.zope.general/61599
From: Simon Michael <simon@...>
Subject: calling satisfied Zwiki users
Newsgroups: gmane.comp.web.zope.general, gmane.comp.web.zope.plone.user
Date: 2009-01-28 23:11:06 GMT (4 weeks, 2 days, 4 hours and 15 minutes ago)

Forwarding this to the Zwiki and ex-Zwiki diaspora. Thanks all!

-Simon

On Jan 28, 2009, at 3:00 PM, Simon Michael wrote:

Marketing.. sure, why not. New Zwiki users are still showing up and a
little more marketing wouldn't hurt.

I think some of us enjoy using Zwiki and I've thought about collecting
some testimonials/quotes. I know when I see a project that has
realistic testimonials from happy users, that really helps motivate me
to try it out.

I don't have much sense of how large/active/plugged in to this page
the Zwiki-using community is, but if you are reading this, are happy
with the software and can write a short testimonial, please send it.
Don't wait, just hit reply now! :)

Testimonials are like a micro-review, typically a short quote. (Longer
reviews are of course welcome too!) They should come from your real
experience with Zwiki, and be honest (negative reviews are also
useful.) Include the name you'd like to appear with the quote; the
strongest testimonials include a real full name and organization. You
might mention whether you are using Zwiki with or without Plone. If I
can collect enough positive ones, I'll start rotating them on the
zwiki.org home page.

*** John Maxwell
We've been using ZWiki as our general purpose web platform for five years
now; its brilliant blend of simplicity and malleability means we've been
able to extend it in a whole bunch of directions: reference library,
blogging platform, discussion forum, classroom support, writing
environment, project tracker, and all-around web content management
tool. We have redesigned our ZWiki-based site from top-to-bottom four
times in five years, and I remain convinced that ZWiki is the most
flexible and capable tool around. - John Maxwell, Canadian Centre for
Studies in Publishing, SFU. http://thinkubator.ccsp.sfu.ca/AboutThinkubator
*** Sascha Welter
One of my cool experiences with Zwiki: I created a site for my father and
I almost never have support questions from him - he's just updating that
site all on his own. He'll be 65 now - not stone old, but still no web hip
youngster any more.
*** Allen Schmidt Sr.
We have been using Zwiki for over 3 years now as a sort of internal
knowledgebase for our group. It has worked out really well and we all like
using it. The issue tracking features are great and it has really helped
keep our small group informed about changes to our site and if offers an
easy way to find out info quickly when we need it.

Thanks for a great project!

Allen Schmidt Sr.
fredericksburg.com
The Free Lance-Star Newspaper
Fredericksburg, Virginia - birthplace of Zope

*** Ed Leafe
It was brain-dead easy to set up, and it has been working well. I've added
a couple of custom formatting things such as <pycode> tags that use
py2html to render code, but otherwise it's been great. Thanks for your
work!
*** Willi Langenberger
Uh, oh, marketing. I think i'm very bad in it. And i fear my english
isnt enough. However, im fine if you write one! Here are some
datapoints:

**** I'm the head of the administrative applications section of the it
 department of the Vienna University of Economics and Business.

   http://www.wu-wien.ac.at/zid/information/abt/vwa
   http://www.wu-wien.ac.at/zid/information/abt/vwa/ma#vw

**** My section has 15 employees and makes the software development for
 the university administration.

**** Our section uses Zope since 2002 and Zwiki since 2004.

**** We use ZWiki as our primary development and administration
 documentation system. Even most of the user documentation is in
 ZWiki.

**** currently there are 750 wiki pages in it.

Let me know, if you have any question about it!
*** Kent Tenney
TWIMC,

In Aug. of 2002 I was involved in the creation of a computer recycling project
and had the good fortune to select Zwiki as the repository of
information about Longrun
http://longrun.zwiki.org/TheLongrunStory

Since it was created in 2002, the wiki has been moved from isp to localhost, to
isp, to localhost, and now to Zwiki's hosting service. There were 59 releases
of the Zwiki software over this time period.

It has gone through periods of heavy use and complete neglect, there are
currently ~1000 pages of stuff.

Throughout it's life, Simon has provided the assistance required to keep the
contents safe and sound. It is truly wonderful (and rare) to have this
degree of continuity and stability.

In the past I have done some programming to integrate Zwiki with other
software tools, and will be revisiting that soon. Zwiki has so many features,
such a nice API, and such good support, it will be fun.

Thanks Simon.

*** Wu
*** jham
*** rdz
*** tessier
*** Vejeta
***
***
***
***
** release notes template
Zwiki 2.x.x 2009/xx/xx
=======================
First public release of Zwiki 2.
	
**Upgrade notes**
	
**Installing**

**Configuring**

**Browsing**

**Editing**

**Mail**

**Feeds**

**Issue tracking**

**General**

**Translations**

** notes
clarify division/integration between fs and wiki docs
publish fs docs online with sphinx(/gitit?)
get epydoc/doxygen working
simpler more focussed wiki docs

* SITES
** notes
profile, speed up, simplify
good stats.. google analytics ?
better free wiki signup/marketing/maintenance

** resolve unicode errors in zope3 wiki

